interface Env {
	TENOR_API_KEY: string;
	TENOR_API_URL: string;
	TENOR_MEDIA_URL: string;
	SIGNAL_STICKERS_URL: string;
	ENCRYPTED_PREVIEW_PUBLIC_KEY_B64: string
	ENCRYPTED_PREVIEW_PRIVATE_KEY_B64: string
}
